name: CI/CD counter app

on:
  push:
    branches: [ main ]
env:
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY  }}
  EC2_INSTANCE_IP: ec2-54-210-128-125.compute-1.amazonaws.com
  DOCKER_COMPOSE_FILE: docker-compose.yaml

jobs:
  Deploy:
#    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create project directory if it does not exist
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ubuntu@${EC2_INSTANCE_IP} '
            cd /home/ubuntu &&
            mkdir -p x-board/backend
          '

      - name: Copy files to EC2 instance
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key && chmod 600 private_key
          scp -r -o StrictHostKeyChecking=no -i private_key src .env.vault Dockerfile docker-compose.yaml package-lock.json package.json ubuntu@${EC2_INSTANCE_IP}:/home/ubuntu/x-board/backend/

      - name: Build and run docker
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ubuntu@${EC2_INSTANCE_IP} '
            cd /home/ubuntu/x-board/backend &&
            sudo docker-compose down &&
            sudo docker-compose up -d
          '
